### ISSUE TITLE
Add test helpers

### ISSUE THREAD

**Issue by MatheusRich** [Fretadao/f_service#6]
- Helper to create results (success and failures)
- Assertions/Expectations (ex: `expect(result).to have_value/have_error(1)`)

Resources:
* https://relishapp.com/rspec/rspec-expectations/v/3-8/docs/custom-matchers/define-a-custom-matcher

**Comment by bvicenzo** [comment]
Implemented in this PR: https://github.com/Fretadao/f_service/pull/35
